// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlACP2RcVNUGfTE5CQJ-3vpI9HFbes_ZM',
    appId: '1:415879844983:web:34087a6669608cac016272',
    messagingSenderId: '415879844983',
    projectId: 'fabricationtracking',
    authDomain: 'fabricationtracking.firebaseapp.com',
    storageBucket: 'fabricationtracking.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ-YalVp6t9h1mhwvdeHcv2_TfQIAKTUI',
    appId: '1:415879844983:android:776889ee6b3aca23016272',
    messagingSenderId: '415879844983',
    projectId: 'fabricationtracking',
    storageBucket: 'fabricationtracking.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLh5JW0jan814lnmJnkzjiDJLuU0-Wpx4',
    appId: '1:415879844983:ios:a4f16e294ca0ff12016272',
    messagingSenderId: '415879844983',
    projectId: 'fabricationtracking',
    storageBucket: 'fabricationtracking.firebasestorage.app',
    iosBundleId: 'com.example.workerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLh5JW0jan814lnmJnkzjiDJLuU0-Wpx4',
    appId: '1:415879844983:ios:a4f16e294ca0ff12016272',
    messagingSenderId: '415879844983',
    projectId: 'fabricationtracking',
    storageBucket: 'fabricationtracking.firebasestorage.app',
    iosBundleId: 'com.example.workerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlACP2RcVNUGfTE5CQJ-3vpI9HFbes_ZM',
    appId: '1:415879844983:web:79529b456476125b016272',
    messagingSenderId: '415879844983',
    projectId: 'fabricationtracking',
    authDomain: 'fabricationtracking.firebaseapp.com',
    storageBucket: 'fabricationtracking.firebasestorage.app',
  );
}
